### PR TITLE
Add option to disable interactive terminal for use in CI

### PR DESCRIPTION
**Pull request by dkomisar**
### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by dholth** [comment]
I would be happy to include this in the upcoming 2.0 release. The argument should be called `--quiet/-q`. You will need to add a test to maintain 100% code coverage.

**Comment by dholth** [comment]
#149

**Comment by dkomisar** [comment]
Thanks, I'll just remove tqdm to keep things simple.

Do you still want me to add the `-q` option? We don't actually want to use that in the build flow since the logging will be readable without tqdm.

**Comment by dholth** [comment]
+1 on no tqdm, no -q option

**Pull request closed without merging**
