### PR TITLE
Gracefully handle missing subcommands.

### LINKED ISSUE #98: cph cannot be called without arguments
Running cph without any arguments results in:

```
(base) [tkoch@host]$ cph
Traceback (most recent call last):
  File "/home/tkoch/anaconda/py39/bin/cph", line 11, in <module>
    sys.exit(main())
  File "/home/tkoch/anaconda/py39/lib/python3.9/site-packages/conda_package_handling/cli.py", line 98, in main
    raise NotImplementedError("Command {} is not implemented".format(args.subparser_name))
NotImplementedError: Command None is not implemented
```

The expected result would be to display user-friendly help text and exit with a non-zero exit code.

### PR DESCRIPTION
**Pull request by jezdez**
Fix #98.

### CODE REVIEW

**Comment by kenodegard** [comment]
Can we use [`required` argument for `add_subparsers`](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_subparsers) instead (depends on Python >=3.7)?

**Comment by jezdez** [comment]
> Can we use [`required` argument for `add_subparsers`](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_subparsers) instead (depends on Python >=3.7)?

Well dang, that's a good catch, yes!

**Comment by jezdez** [comment]
OTOH the result looks like this (and it results in error code 2):

```
❯ cph
usage: cph [-h] [-V] {extract,x,create,c,verify,v,transmute,t} ...
cph: error: the following arguments are required: subparser_name
```

Before it looked like this:

```
❯ cph
No subcommand provided. Please try again.
usage: cph [-h] [-V] {extract,x,create,c,verify,v,transmute,t} ...

options:
  -h, --help            show this help message and exit
  -V, --version         Show the conda-package-handling version number and exit.

subcommands:
  {extract,x,create,c,verify,v,transmute,t}
    extract (x)         extract package contents
    create (c)          bundle files into a package
    verify (v)          verify converted files against their reference
    transmute (t)       convert from one package type to another
```

**Comment by kenodegard** [comment]
🤷🏻‍♂️ I'd choose the option with the least code

**Review by kenodegard — APPROVED** [review]
lol did not realize it would reformat everything

**Pull request merged**
